#https://getinthere.tistory.com/20

server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create  #create:프로젝트 실생 시 마다 새로 생성, update:기존데이터에 append, none:사용안함. -> 첫번째에만 create 그 후엔 update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity(table) 생성시 생성할 전략.
      use-new-id-generator-mappings: false  #JPA가 사용하는 기본 DB 넘버링 전략설정 사용여부.
    show-sql: true  #sql로그 출력
    properties:
      hibernate.format_sql: true  #로그 pretty print

  jackson:
    serialization:
      fail-on-empty-beans: false